### ISSUE TITLE
PJE - PROCESSO ELETRÔNICO GERAÇÃO DE TAG ASSINATURA

### ISSUE THREAD

**Issue by miltonmagalhaes** [phelipealves/assinaturadigitaljavascript#1]
Ola Phelipe 
Seu projeto é sensacional e, acho, poderá me ajudar a superar uma imensa dificuldade para a geração de Assinatura Digital em documentos do PJE - Processo Eletrônico.
Se puderes fazer contato comigo diretamente te agradeço. miltonmagalhaes@hotmail.com

**Comment by phelipealves** [comment]
Oi @miltonmagalhaes, 
Agradeço por ter gostado do projeto, e me desculpe pela dermora do contato.
Foi encaminhado o email.
Estou disponível para sanar qualquer dúvida e ajudar a melhorar o projeto.
