### ISSUE TITLE
alterar readme.md

### ISSUE THREAD

**Issue by fredguth** [phelipealves/assinaturadigitaljavascript#3]
Sugiro que deixe claro no readme.md que este projeto não chega a ter as funcionalidades que o demo sugere que é capaz (ex: leitura do certificado do usb token).

Além disso, seria bom referenciar http://tutorialzine.com/2013/11/javascript-file-encrypter/
uma vez que o código se baseou nele.

**Comment by phelipealves** [comment]
Obrigado pela dica @fredguth. 
Referencia adicionada.
